from django.test import SimpleTestCase
from django.urls import reverse, resolve
from products.views import ProductViewSet


# Test case for URL routing
class TestUrls(SimpleTestCase):
    
    # test to verify the list and detail URL patterns
    def test_list_urls(self):
        url = reverse('product-list') # the name generated by DefaultRouter
        print(resolve(url))
        self.assertEqual(resolve(url).url_name, 'product-list') # verify the URL name
        
    # test to verify the detail URL pattern
    def test_detail_urls(self):
        url = reverse('product-detail', args=[1]) # the name generated by DefaultRouter
        print(resolve(url))
        self.assertEqual(resolve(url).url_name, 'product-detail') # verify the URL name