# Generated by Django 5.2.6 on 2025-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("when_created", models.DateTimeField(auto_now_add=True)),
                ("when_to_complete", models.DateTimeField(blank=True, null=True)),
                ("when_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
    ]
